title: 'Sagres'
subTitle: 'Sagres'
primary_color: '#ffffff'
secondary_color: '#006600'
logo: 'modules/custom/sagres/images/cienciapt_logo_150.png'
footer_logo: 'modules/custom/sagres/images/footer.png'
image_1: 'modules/custom/sagres/images/img1.jpg'
image_2: 'modules/custom/sagres/images/img2.jpg'
image_3: 'modules/custom/sagres/images/img3.jpg'
partners_logo: 'modules/custom/sagres/images/graxiom.png'
